name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Code quality with black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ". --check --line-length 79"
      - name: Check dependencies cache
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-modules
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # - name: Install scipy dependencies
      #   run: |
      #     sudo apt-get install gfortran libopenblas-dev liblapack-dev
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install azureml-sdk[automl] --ignore-installed onnxruntime
#          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
#       - name: Test with pytest
#         run: |
#           pip install pytest
#           pip install pytest-cov
#           pytest --cov=./ --cov-report=xml
#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v1
      - name: Begin pipeline
        run: |
          python test.py
